name: boring_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  dio: ^5.1.0
  equatable: ^2.0.5
  flutter_pagewise: ^2.0.4
  url_launcher: ^6.1.10
  getwidget: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/busywork.jpg
    - assets/charity.jpg
    - assets/cooking.jpg
    - assets/diy.jpg
    - assets/education.jpg
    - assets/label.png
    - assets/music.jpg
    - assets/recreational.jpg
    - assets/relaxation.jpg
    - assets/social.jpg
    - assets/background.png
